@startuml
Alice -> Bob: Authentication Request
Bob -> Lucy: Get the data from DB

Lucy -> Bob: Return the data
Bob --> Alice: Authentication Response

Alice -> Bob: Second Request
Bob --> Alice: SecondResponse

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml